spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http:localhost:4200'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
